APP_VERSION = "v1.6.3-macos.3"
UPDATE_CHANNEL = "release"
REPOSITORY_URL = "https://github.com/MarchPhantasia/BiliBiliDropsMiner"
LATEST_RELEASE_API = "https://api.github.com/repos/MarchPhantasia/BiliBiliDropsMiner/releases/latest"
RELEASES_URL = "https://github.com/MarchPhantasia/BiliBiliDropsMiner/releases/latest"
